/**
 * M.Sc Computer Science 2nd Year Student List
 * Complete list of students with Registration Number and Name
 */

export const MSC_CS_2ND_YEAR_STUDENTS = [
    { registerNumber: '24MSCSCPY0001', name: 'PREMA NANCY' },
    { registerNumber: '24MSCSCPY0002', name: 'THAGDE AVINASH' },
    { registerNumber: '24MSCSCPY0003', name: 'RAMYA V' },
    { registerNumber: '24MSCSCPY0004', name: 'NAVEENA V S' },
    { registerNumber: '24MSCSCPY0005', name: 'BITAN MAJUMDER' },
    { registerNumber: '24MSCSCPY0006', name: 'KOMMU RUCHITHA' },
    { registerNumber: '24MSCSCPY0007', name: 'JANANIE N' },
    { registerNumber: '24MSCSCPY0008', name: 'AARTHIKA M' },
    { registerNumber: '24MSCSCPY0010', name: 'HEMALATHA M' },
    { registerNumber: '24MSCSCPY0011', name: 'GAYATHRI M' },
    { registerNumber: '24MSCSCPY0012', name: 'SAGGITHYA R P' },
    { registerNumber: '24MSCSCPY0013', name: 'PATIVADA NAVEEN KUMAR' },
    { registerNumber: '24MSCSCPY0014', name: 'ABHINAV V' },
    { registerNumber: '24MSCSCPY0015', name: 'THOTAKURI SUJEEV JOHN' },
    { registerNumber: '24MSCSCPY0016', name: 'PRABAL TALUKDAR' },
    { registerNumber: '24MSCSCPY0017', name: 'PRAKASH RAJ S' },
    { registerNumber: '24MSCSCPY0018', name: 'PREETHI D' },
    { registerNumber: '24MSCSCPY0019', name: 'SHEELA DEVI V' },
    { registerNumber: '24MSCSCPY0020', name: 'DHANUSH S' },
    { registerNumber: '24MSCSCPY0021', name: 'NILA' },
    { registerNumber: '24MSCSCPY0022', name: 'SYED AJMAL S' },
    { registerNumber: '24MSCSCPY0023', name: 'JOSH JOHN JOSEPH' },
    { registerNumber: '24MSCSCPY0024', name: 'SANJAI S' },
    { registerNumber: '24MSCSCPY0025', name: 'ROSELINE SWETHA T' },
    { registerNumber: '24MSCSCPY0026', name: 'THALLURI SRIJA' },
    { registerNumber: '24MSCSCPY0027', name: 'KRISHNARAJ E' },
    { registerNumber: '24MSCSCPY0028', name: 'FATHIMMATH NAHLA NM' },
    { registerNumber: '24MSCSCPY0029', name: 'SHAHNA K' },
    { registerNumber: '24MSCSCPY0030', name: 'MURSHIDUL HIBHAN' },
    { registerNumber: '24MSCSCPY0031', name: 'JANGAM RAKESH' },
    { registerNumber: '24MSCSCPY0032', name: 'K VARUN TEJA' },
    { registerNumber: '24MSCSCPY0033', name: 'CHURCHILL SAMUEL E' },
    { registerNumber: '24MSCSCPY0034', name: 'VASEEM N' },
    { registerNumber: '24MSCSCPY0037', name: 'ABUSALEEM S' },
    { registerNumber: '24MSCSCPY0038', name: 'VELMURUGAN G' },
    { registerNumber: '24MSCSCPY0039', name: 'ANJU ANEESH' },
    { registerNumber: '24MSCSCPY0040', name: 'ADARSH SINGH B' },
    { registerNumber: '24MSCSCPY0041', name: 'APARNA C' },
    { registerNumber: '24MSCSCPY0042', name: 'NAVEEN P' },
    { registerNumber: '24MSCSCPY0043', name: 'SHARISHNA' },
    { registerNumber: '24MSCSCPY0044', name: 'RIFNA K' },
    { registerNumber: '24MSCSCPY0045', name: 'SHAHEEL P' },
    { registerNumber: '24MSCSCPY0046', name: 'RAJESH V' },
    { registerNumber: '24MSCSCPY0047', name: 'FELIX G' },
    { registerNumber: '24MSCSCPY0048', name: 'ARAVINDAN N' },
    { registerNumber: '24MSCSCPY0049', name: 'NANDHAKUMAR S' },
    { registerNumber: '24MSCSCPY0050', name: 'KARTHICK P' },
    { registerNumber: '24MSCSCPY0051', name: 'SUBASINI S' },
    { registerNumber: '24MSCSCPY0052', name: 'THIRUKUMARAN S' },
    { registerNumber: '24MSCSCPY0053', name: 'MIRIYALA MOUNIKA' },
    { registerNumber: '24MSCSCPY0054', name: 'VISHNU J' },
    { registerNumber: '24MSCSCPY0055', name: 'ASHWIN K SHAJI' },
    { registerNumber: '24MSCSCPY0056', name: 'YESURAJ G' },
    { registerNumber: '24MSCSCPY0057', name: 'JANARTHANAN S' },
    { registerNumber: '24MSCSCPY0058', name: 'SORYAH A S' },
    { registerNumber: '24MSCSCPY0059', name: 'ALYAZAH.SM' },
    { registerNumber: '24MSCSCPY0060', name: 'KISHORE S' },
    { registerNumber: '24MSCSCPY0061', name: 'ABIRAMI G' },
    { registerNumber: '24MSCSCPY0063', name: 'AMEEN AHSAN N' },
    { registerNumber: '24MSCSCPY0064', name: 'DEVANATHAN T' },
    { registerNumber: '24MSCSCPY0065', name: 'DONELL DARIN A' },
    { registerNumber: '24MSCSCPY0066', name: 'NARENDRA K' },
    { registerNumber: '24MSCSCPY0067', name: 'AARTHI J' },
    { registerNumber: '24MSCSCPY0068', name: 'DHARANI T' },
];

/**
 * Helper function to format student data for Firestore
 */
export const formatMscCS2ndYearStudentData = (registerNumber, name) => ({
    registerNumber: registerNumber.toUpperCase(),
    name: name.trim(),
    course: 'PG',
    program: 'M.Sc CS',
    year: 2,
    section: 'A',
    isActive: true,
    createdAt: new Date().toISOString(),
});
