/**
 * Staff List - All 19 Faculty Members
 * Name, Email, Password, UID
 */

export const STAFF_LIST = [
    {
        name: 'Dr. R. Subramanian',
        email: 'rsubramanian.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'LaCFcdzzlfVTV7aQBq10RmATR962',
        imageKey: 'r_subramanian',
        photoPath: 'Staff Photos/subramaniam-csc-profile.jpeg',
        designation: 'Professor',
        department: 'Computer Science',
        subjectsHandled: ['Artificial Intelligence', 'Machine Learning'],
        courseCoordinator: 'Research Programmes',
    },
    {
        name: 'Dr. T. Chithralekha',
        email: 'tchithralekha.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'QbycWm2pAeRh6m1hikh1fTRMEcm2',
        imageKey: 't_chithralekha',
        photoPath: 'Staff Photos/Chithralekha-Balamurugan-768x1024.jpg',
        designation: 'Professor',
        department: 'Computer Science',
        subjectsHandled: ['Data Mining', 'Big Data Analytics'],
        courseCoordinator: 'M.Sc Programmes',
    },
    {
        name: 'Dr. S. Sivasathya',
        email: 'ssivasathya.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'bjbTINTWCKdwZBOsf4x795CPM7J2',
        imageKey: 's_sivasathya',
        photoPath: 'Staff Photos/DSC_1112-copy-Sivasathya-Sundaram-scaled-e1593754969122-767x1024.jpg',
        designation: 'Professor',
        department: 'Computer Science',
        subjectsHandled: ['Software Engineering', 'Object Oriented Systems'],
        courseCoordinator: 'B.Tech Programmes',
    },
    {
        name: 'Dr. S. K. V. Jayakumar',
        email: 'head.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'AQAyKIo3CTWGxUGBcsmRcNaNeK02',
        imageKey: 'skv_jayakumar',
        photoPath: 'Staff Photos/Profile-Pic-Dr.-SKV-Jayakumar.jpg',
        designation: 'Professor',
        department: 'Computer Science',
        subjectsHandled: ['Software Engineering', 'DBMS', 'Cloud Computing'],
        courseCoordinator: 'Department Head',
    },
    {
        name: 'Dr. K. Suresh Joseph',
        email: 'ksureshjoseph.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'bqyyL7oKF2grQY2ByK4iQnWyn9a2',
        imageKey: 'k_suresh_joseph',
        photoPath: 'Staff Photos/suresh-joseph-profile.jpeg',
        designation: 'Professor',
        department: 'Computer Science',
        subjectsHandled: ['Network Security', 'Cryptography'],
        courseCoordinator: 'M.Tech NIS',
    },
    {
        name: 'Dr. S. Ravi',
        email: 'sravi.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: '08Eo6sQGjMUNLqlXoedUvJKgxLE2',
        imageKey: 's_ravi',
        photoPath: 'Staff Photos/Dr-Ravi-Subban-23-SEP-2024-Dr.RAVI-S.jpg',
        designation: 'Professor',
        department: 'Computer Science',
        subjectsHandled: ['Distributed Systems', 'Operating Systems'],
        courseCoordinator: 'MCA Programme',
    },
    {
        name: 'Dr. M. Nandhini',
        email: 'mnandhini.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'G7ThTfwjgXQXtDeUMvt8VhzG3Vj2',
        imageKey: 'm_nandhini',
        photoPath: 'Staff Photos/Profile-PhotoDr.-M.-Nandhini.png',
        designation: 'Professor',
        department: 'Computer Science',
        subjectsHandled: ['Data Structures', 'Algorithms'],
        courseCoordinator: 'B.Sc Computer Science',
    },
    {
        name: 'Dr. Pothula Sujatha',
        email: 'psujatha.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'yF2LwzcceaVvmdCnQhHDAo4AvkO2',
        imageKey: 'pothula_sujatha',
        photoPath: 'Staff Photos/WhatsApp-Image-2025-05-11-at-00.47.51-Dr.POTHULA-SUJATHA-864x1024.jpeg',
        designation: 'Professor',
        department: 'Computer Science',
        subjectsHandled: ['Computer Networks', 'Wireless Networks'],
        courseCoordinator: 'M.Tech CSE',
    },
    {
        name: 'Dr. P. Shanthi Bala',
        email: 'pshanthi.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: '730SDajTUXZD4SYRJyYc3zqIl792',
        imageKey: 'p_shanthi_bala',
        photoPath: 'Staff Photos/Shanthi-Bala-Shanthi-Bala-P.jpg',
        designation: 'Professor',
        department: 'Computer Science',
        subjectsHandled: ['Compiler Design', 'Programming Languages'],
        courseCoordinator: 'Academic Coordinator',
    },
    {
        name: 'Dr. R. Sunitha',
        email: 'rsunitha.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'XCaaiFHMmBZRbq6ybgRAfjraEki1',
        imageKey: 'r_sunitha',
        photoPath: 'Staff Photos/Profile-PicDr.SUNITHA-R-771x1024.jpeg',
        designation: 'Associate Professor',
        department: 'Computer Science',
        subjectsHandled: ['Database Systems', 'Data Warehousing'],
        courseCoordinator: 'M.Sc Data Science',
    },
    {
        name: 'Dr. K. S. Kuppusamy',
        email: 'kskuppusamy.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'GCKQctq2qqPPc9oDLrD3ePkVonq1',
        imageKey: 'ks_kuppusamy',
        photoPath: 'Staff Photos/K-S-Kuppusamy-Dr.KUPPUSAMY-K.S-e1747396720688-1002x1024.jpg',
        designation: 'Associate Professor',
        department: 'Computer Science',
        subjectsHandled: ['Image Processing', 'Pattern Recognition'],
        courseCoordinator: 'Research Coordination',
    },
    {
        name: 'Dr. V. Uma',
        email: 'vuma.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'YQ7tNqdGQKVEfhSQYAPt9MhtkWX2',
        imageKey: 'v_uma',
        photoPath: 'Staff Photos/uma-photo-good-Uma-V.jpg',
        designation: 'Associate Professor',
        department: 'Computer Science',
        subjectsHandled: ['Operating Systems', 'Linux Programming'],
        courseCoordinator: 'UG Labs',
    },
    {
        name: 'Dr. T. Vengattaraman',
        email: 'tvengattaraman.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'iXQaGdm2qqbJ7HaQe433wvuSzD42',
        imageKey: 't_vengattaraman',
        photoPath: 'Staff Photos/ProfilePicture-TVengattaraman.jpg',
        designation: 'Associate Professor',
        department: 'Computer Science',
        subjectsHandled: ['Web Technologies', 'Software Testing'],
        courseCoordinator: 'Placement & Industry Connect',
    },
    {
        name: 'R. P. Seenivasan',
        email: 'rpseenivasan.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: '4aQmeR7TGSOVFPINAhrVYYVn8Qt2',
        imageKey: 'rp_seenivasan',
        photoPath: 'Staff Photos/seenivasan-profile.jpeg',
        designation: 'Assistant Professor',
        department: 'Computer Science',
        subjectsHandled: ['C Programming', 'Data Structures'],
        courseCoordinator: 'UG Tutorials',
    },
    {
        name: 'Dr. T. Sivakumar',
        email: 'tsivakumar.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'CDgpKYb2NsVYebbxeWz0shNkf9X2',
        imageKey: 't_sivakumar',
        photoPath: 'Staff Photos/Profile-PhotoDr.-T.-Sivakumar-e1753355380943.png',
        designation: 'Assistant Professor',
        department: 'Computer Science',
        subjectsHandled: ['Java Programming', 'Web Applications'],
        courseCoordinator: 'Web Technologies',
    },
    {
        name: 'Dr. M. Sathya',
        email: 'msathya.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'LwB4M934wPcBK9oJIIxzcsHMBZe2',
        imageKey: 'm_sathya',
        photoPath: 'Staff Photos/Profile-Photo-Dr.-M.-Sathya-773x1024.jpg',
        designation: 'Assistant Professor',
        department: 'Computer Science',
        subjectsHandled: ['Python Programming', 'Data Science'],
        courseCoordinator: 'Data Science Labs',
    },
    {
        name: 'Dr. S. L. Jayalakshmi',
        email: 'sljayalakshmi.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'TwJ8xqWQGmYghfA83gRZSScD9fy2',
        imageKey: 'sl_jayalakshmi',
        photoPath: 'Staff Photos/Profile-Pic-Dr.-S.-L.-Jayalakshmi.jpg',
        designation: 'Assistant Professor',
        department: 'Computer Science',
        subjectsHandled: ['Computer Architecture', 'Digital Logic'],
        courseCoordinator: 'Hardware Labs',
    },
    {
        name: 'Dr. Krishnapriya',
        email: 'krishnapriya.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'qY3oLx8luEW1qbWmyMWqA5nKEno1',
        imageKey: 'krishnapriya',
        photoPath: 'Staff Photos/Profile-Photo-Dr.Krishnapriya-Ganesan-708x1024.jpg',
        designation: 'Assistant Professor',
        department: 'Computer Science',
        subjectsHandled: ['Operating Systems', 'Database Systems'],
        courseCoordinator: 'Internal Assessment',
    },
    {
        name: 'Dr. Sukhvinder Singh',
        email: 'ssingh.csc@pondiuni.ac.in',
        password: 'Pass@123',
        uid: 'K6OEAt6c1rTlG9VxbizzPZhK8Bj2',
        imageKey: 'sukhvinder_singh',
        photoPath: 'Staff Photos/Sukhvinder-e1747650879391.jpg',
        designation: 'Assistant Professor',
        department: 'Computer Science',
        subjectsHandled: ['Artificial Intelligence', 'Machine Learning'],
        courseCoordinator: 'AI & ML Programmes',
    },
];

/**
 * Format staff data for Firestore
 */
export const formatStaffData = (staff) => ({
    name: staff.name.trim(),
    email: staff.email.toLowerCase().trim(),
    password: staff.password,
    uid: staff.uid,
    imageKey: staff.imageKey,
    photoPath: staff.photoPath,
    designation: staff.designation || '',
    department: staff.department || 'Computer Science',
    subjectsHandled: staff.subjectsHandled || [],
    courseCoordinator: staff.courseCoordinator || null,
    role: 'Staff',
    isActive: true,
    passwordChanged: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
});

